global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: infra-app
    scheme: https
    static_configs:
      - targets:
          - order-api-546580006264.asia-south1.run.app
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
